### ISSUE TITLE
with latest das environment installation I cannot open the gui on ubuntu

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/das#18]
after `conda update conda`, I ran: `conda create python=3.8 das -c conda-forge -c ncb -n das`. When trying to execute `das gui` I get:

```
Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/das/bin/das", line 7, in <module>
    from das.cli import main
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/das/lib/python3.8/site-packages/das/cli.py", line 3, in <module>
    from . import train, predict, train_tune
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/das/lib/python3.8/site-packages/das/train_tune.py", line 17, in <module>
    import keras_tuner as kt
ModuleNotFoundError: No module named 'keras_tuner'
```
with conda list, i see that keras-tuner is installed (version 1.0.1). I ran `conda install -c conda-forge keras-tuner` (and also tried it with a pip install another time), for `das gui` I get now:

```
E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (xxx): /proc/driver/nvidia/version does not exist
The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 368 requests (368 known processed) with 0 events remaining.
```

**Comment by postpop** [comment]
These are two independent errors. First part of the bug report should be fixed in the latest release. Opened new issue #20 for the second part.
