### ISSUE TITLE
Create a folder in /res when saving annotations

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/das#22]
When I click File > Save annotations and there is no localhost folder in /res, it throws the following error (put no pop up or so). It would be cool if either a localhost folder is created in res/ or if a pop up tells that the annotations.csv could not be saved.

Saving annotations to /home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/dat/localhost-20220217_090732/home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/res/localhost-20220217_090732/localhost-20220217_090732_annotations.csv.
Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 1651, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 214, in save_annotations
    self.export_to_csv(savefilename)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 259, in export_to_csv
    df.to_csv(savefilename, index=False)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/pandas/core/generic.py", line 3563, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1180, in to_csv
    csv_formatter.save()
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/pandas/io/common.py", line 697, in get_handle
    check_parent_directory(str(handle))
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xarray_behave/lib/python3.8/site-packages/pandas/io/common.py", line 571, in check_parent_directory
    raise OSError(fr"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/dat/localhost-20220217_090732/home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/res/localhost-20220217_090732'

**Comment by postpop** [comment]
fixed by [janclemenslab/das/#fd652a2d23daf042d9357bd14a0c085901ed4274](https://github.com/janclemenslab/xarray-behave/commit/fd652a2d23daf042d9357bd14a0c085901ed4274)
