### ISSUE TITLE
possible to use 'das train' with non GUI version?

### ISSUE THREAD

**Issue by AFurryBear** [janclemenslab/das#29]
is it possible to use 'das train' and 'das predict' in command line to use non GUI version? 
or should i run with python script? 

below is error info: 
`ERROR:root:Failed to import GUI. You can still use the non GUI part of DAS.
Traceback (most recent call last):
  File "/opt/conda/envs/das/lib/python3.8/site-packages/das/cli.py", line 62, in main
    import xarray_behave.gui.app
  File "/opt/conda/envs/das/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 27, in <module>
    from qtpy import QtGui, QtCore, QtWidgets
  File "/opt/conda/envs/das/lib/python3.8/site-packages/qtpy/QtGui.py", line 30, in <module>
    from PyQt5.QtGui import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by postpop** [comment]
Yes, the GUI is just a wrapper around these commands. You can get information on usage with `das train --help` and `das predict --help`. Happy to help if you have more questions.

Could you share the output of `das version` so we can identify the cause of the bug? Alternatively, you could also try installing DAS with python 3.9 instead of 3.8 as is currently the default:
```shell
mamba create python=3.9 das -c conda-forge -c ncb -n das
```

**Comment by AFurryBear** [comment]
I tried with python=3.9 but it still wont work without GUI. besides, i didn't see parameters in `das train --help ` directed means 'non gui', could u help specifying it? 

Below is output for das version
`(das) root@2233ac847353:/# das version
2022-05-04 14:47:21.684738: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-04 14:47:25.180773: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-04 14:47:25.181070: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-04 14:47:25.181121: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-04 14:47:25.181191: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (2233ac847353): /proc/driver/nvidia/version does not exist
ERROR:root:Failed to import GUI. You can still use the non GUI part of DAS.
Traceback (most recent call last):
  File "/opt/conda/envs/das/lib/python3.9/site-packages/das/cli.py", line 62, in main
    import xarray_behave.gui.app
  File "/opt/conda/envs/das/lib/python3.9/site-packages/xarray_behave/gui/app.py", line 27, in <module>
    from qtpy import QtGui, QtCore, QtWidgets
  File "/opt/conda/envs/das/lib/python3.9/site-packages/qtpy/QtGui.py", line 30, in <module>
    from PyQt5.QtGui import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
The following versions are available to DAS:
  DAS v0.25.1
     GUI is NOT AVAILABLE

  tensorflow v2.4.1
  keras v2.4.0
     GPU is NOT AVAILABLE

  python v3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:22:55)
[GCC 10.3.0]
  pandas v1.4.2
  numpy v1.21.6
  h5py v2.10.0
  scipy v1.7.3
  scikit-learn v1.0.2
  xarray v2022.3.0`

**Comment by postpop** [comment]
Could you try starting the GUI like that:
```shell
QT_API=pyside2 das gui
```

This will force use of another GUI backend (PySide2 instead of PyQt5) which might work better.
