### ISSUE TITLE
Error when training with nb_hist = 2048 in gui, but not via local py script or colab script

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#37]
Dear Jan & team, 

Thanks for being so responsive with my many questions thus far! 

I think I've found another potential bug (?) or at least an error I'm consistently getting when trying to train a model with nb_hist = 2048. I tried training in 3 possible ways (GUI, py script in colab,  py script run via command-line) and found that the error only occurs when I run the training in the GUI. 

While training from the GUI with nb_hist = 1024, everything works as expected. But setting this value to 2048 yields the following error: 

```
INFO:das.train:Loading data from F:/Ava/Experiment_2/Exp2_DAS_selections/training_set.npy.
INFO:das.train:Versioning the data:
INFO:das.train:   MD5 hash of F:/Ava/Experiment_2/Exp2_DAS_selections/training_set.npy is
INFO:das.train:   c7dea09bbf41af8e387916c18dfff10a
INFO:das.train:Parameters:
INFO:das.train:{'data_dir': 'F:/Ava/Experiment_2/Exp2_DAS_selections/training_set.npy', 'x_suffix': '', 'y_suffix': '', 'save_dir': 'F:/Ava/Experiment_2/Exp2_DAS_selections/training_set.res', 'save_prefix': '', 'save_name': None, 'model_name': 'tcn_stft', 'nb_filters': 32, 'kernel_size': 16, 'nb_conv': 4, 'use_separable': [False, False, False], 'nb_hist': 2048, 'ignore_boundaries': True, 'batch_norm': True, 'nb_pre_conv': 4, 'pre_nb_dft': 64, 'pre_kernel_size': 3, 'pre_nb_filters': 16, 'pre_nb_conv': '16', 'upsample': True, 'dilations': [1, 2, 4, 8, 16], 'nb_lstm_units': 0, 'verbose': 2, 'batch_size': 32, 'nb_epoch': 100, 'learning_rate': 0.0001, 'reduce_lr': False, 'reduce_lr_patience': 5, 'fraction_data': None, 'first_sample_train': 0, 'last_sample_train': None, 'first_sample_val': 0, 'last_sample_val': None, 'seed': None, 'batch_level_subsampling': False, 'augmentations': None, 'tensorboard': False, 'wandb_api_token': None, 'wandb_project': None, 'wandb_entity': None, 'log_messages': True, 'nb_stacks': 2, 'with_y_hist': True, 'balance': False, 'version_data': True, 'post_opt': False, 'fill_gaps_min': None, 'fill_gaps_max': None, 'fill_gaps_steps': None, 'min_len_min': None, 'min_len_max': None, 'min_len_steps': None, 'resnet_compute': False, 'resnet_train': False, 'sample_weight_mode': 'temporal', 'data_padding': 64, 'return_sequences': True, 'stride': 1920, 'y_offset': 0, 'output_stride': 1, 'class_names': ['noise', 'comm', 'echo'], 'class_types': ['segment', 'segment', 'segment'], 'data_folder': 'F:/Ava/Experiment_2/Exp2_DAS_selections/training_set', 'data_splits': {'test': 0.2, 'train': 0.6, 'val': 0.2}, 'delete_intermediate_store': True, 'event_std_seconds': 0.0016, 'file_splits': {}, 'filename_endsample_test': [], 'filename_endsample_train': [], 'filename_endsample_val': [], 'filename_startsample_test': [], 'filename_startsample_train': [], 'filename_startsample_val': [], 'filename_test': [], 'filename_train': [], 'filename_val': [], 'gap_seconds': 0.0, 'make_single_class_datasets': False, 'samplerate_x_Hz': 250000.0, 'samplerate_y_Hz': 250000.0, 'split_in_two': False, 'store_folder': 'F:/Ava/Experiment_2/Exp2_DAS_selections/training_set.npy', 'file_split_dict': {}, 'data_hash': 'c7dea09bbf41af8e387916c18dfff10a', 'nb_freq': 1, 'nb_channels': 1, 'nb_classes': 3}
INFO:das.train:Preparing data
INFO:das.train:Training data:
INFO:das.train:   AudioSequence with 411 batches each with 32 items.
   Total of 25260018 samples with
   each x=(1,) and
   each y=(3,)
INFO:das.train:Validation data:
INFO:das.train:   AudioSequence with 137 batches each with 32 items.
   Total of 8420006 samples with
   each x=(1,) and
   each y=(3,)
INFO:das.train:building network
Traceback (most recent call last):
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\utils.py", line 222, in run
    self.fn(*self.args, **self.kwargs)
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\das\train.py", line 361, in train
    model = models.model_dict[model_name](**params)
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\das\models.py", line 109, in tcn_stft
    x = tcn_layer.TCN(nb_filters=nb_filters,
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\das\tcn\tcn.py", line 152, in __init__
    use_separable.extend(use_separable[-1] * nb_stacks)
TypeError: 'int' object is not iterable
```

I initially though the problem may have been due to memory constraints (and that the int not iterable error may be just due to it breaking at an uninformative point). 

I don't think this is the case however, as running an almost identical model with nb_hist = 2048 via the terminal works fine (at least, starts/is still running). 

In addition, trying a model with nb_hist = 4096 from the GUI gets past the above error message and begins training, then crashes (this time, I believe, due to memory overload). 

I'm a bit puzzled by why this parameter should derail the GUI-originated training. I'll report back if I discover that there's anything else I've been doing that might be causing the issue. 

Thanks!

For reference, my system info is: 

```
INFO:das.cli:  Windows-10-10.0.19041-SP0
INFO:das.cli:  DAS v0.26.6
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.33.0
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.6.0
INFO:das.cli:  keras v2.6.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
INFO:das.cli:  pandas v1.4.2
INFO:das.cli:  numpy v1.22.4
INFO:das.cli:  h5py v3.6.0
INFO:das.cli:  scipy v1.8.1
INFO:das.cli:  scikit-learn v1.1.1
INFO:das.cli:  xarray v2022.3.0
```

**Comment by avakiai** [comment]
I tried to replicate this error and I wasn't able to - trying to train a new model later with similar parameters from the GUI launched fine. 
Apologies for the many open issues. It may be that this was just an error on my end.

**Comment by postpop** [comment]
I also failed to replicate the issue - was probably something else that caused this.
And please keep the issues coming - thanks for the feedback and for spotting bugs!
