### ISSUE TITLE
Memory+ errors when predicting - tips for optimization?

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#40]
Hi Jan, 

I'm encountering a (possibly memory) issue when trying to get to das to predict call events via the command line (with a custom script), which returns some cryptic error messages. 

It looks like it enters into the process as expected, then may be encountering some issues with the GPU driver or with tensorflow. I wonder if it's just a memory issue breaking at a strange point, since the first segment it throws up is the duration of the whole file (0 - 449.94 s). 

```
(das) C:\Users\Ava Kiai\OneDrive - Johann Wolfgang Goethe Universität\#Bat Lab\_Projects\colony_jam\Experiment_2\2-call_detection_and_classifier_model>python predict_v1.py "E:\Ava\Experiment_2\Exp2_DAS_selections\test_set\outtest_set" "E:\Ava\Experiment_2\Exp2_DAS_selections\training_set_v2.res\20220804_110323_model.h5" -0
WARNING:root:No tensorflow-probability.
data from: E:\Ava\Experiment_2\Exp2_DAS_selections\test_set\outtest_set
model from: E:\Ava\Experiment_2\Exp2_DAS_selections\training_set_v2.res\20220804_110323_model.h5
loading model 20220804_110323

rec2021-08-23_17-37-00_02_04.wav
reading audio file...
predict...
         segment 0: [  0.   449.94] s...
2022-08-10 16:34:44.131524: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-10 16:34:45.102154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1249 MB memory:  -> device: 0, name: NVIDIA GeForce MX450, pci bus id: 0000:01:00.0, compute capability: 7.5
2022-08-10 16:34:45.829214: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-08-10 16:34:47.445444: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2022-08-10 16:34:49.159561: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2022-08-10 16:34:49.159757: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at conv_ops.cc:1272 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "C:\Users\Ava Kiai\OneDrive - Johann Wolfgang Goethe Universität\#Bat Lab\_Projects\colony_jam\Experiment_2\2-call_detection_and_classifier_model\predict_v1.py", line 136, in <module>
    events, segments, class_probabilities, class_names = das.predict.predict(
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\das\predict.py", line 343, in predict
    class_probabilities = predict_probabililties(x, model, params, verbose, prepend_data_padding)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\das\predict.py", line 28, in predict_probabililties
    y_pred = model.predict(pred_gen, verbose=verbose)  # run the network
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1749, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\eager\def_function.py", line 956, in _call
    return self._concrete_stateful_fn._call_flat(
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
         [[node TCN/conv1d/conv1d (defined at \.conda\envs\das\lib\site-packages\das\predict.py:28) ]] [Op:__inference_predict_function_2194]

Function call stack:
predict_function

2022-08-10 16:34:49.410589: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

(das) C:\Users\Ava Kiai\OneDrive - Johann Wolfgang Goethe Universität\#Bat Lab\_Projects\colony_jam\Experiment_2\2-call_detection_and_classifier_model>
(das) C:\Users\Ava Kiai\OneDrive - Johann Wolfgang Goethe Universität\#Bat Lab\_Projects\colony_jam\Experiment_2\2-call_detection_and_classifier_model>
```

Note that I get a different, plain memory error if I run the prediction command from the GUI:
```
INFO:root:Predicting song using DAS:
INFO:root:Loading model from E:/Ava/Experiment_2/Exp2_DAS_selections/training_set_v2.res/20220804_110323.
2022-08-10 17:03:25.063690: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-08-10 17:03:25.491788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1249 MB memory:  -> device: 0, name: NVIDIA GeForce MX450, pci bus id: 0000:01:00.0, compute capability: 7.5
INFO:root:   Loading data from E:/Ava/Experiment_2/Exp2_DAS_selections/test_set/outtest_set\rec2021-08-23_17-37-00_02_04.wav.
INFO:root:   Annotating using model at E:/Ava/Experiment_2/Exp2_DAS_selections/training_set_v2.res/20220804_110323.
2022-08-10 17:03:26.023220: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-08-10 17:03:27.022580: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2022-08-10 17:03:27.595744: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2
2022-08-10 17:03:27.596390: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2
2022-08-10 17:03:27.596901: W tensorflow/stream_executor/gpu/asm_compiler.cc:77] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas.exe --version
2022-08-10 17:03:27.602882: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2
2022-08-10 17:03:27.603240: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
1191/1772 [===================>..........] - ETA: 39s2022-08-10 17:04:50.969756: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 512.00M (536870912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2022-08-10 17:04:50.995580: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 460.80M (483183872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2022-08-10 17:04:51.018966: I tensorflow/stream_executor/cuda/cuda_driver.cc:732] failed to allocate 414.72M (434865664 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
1772/1772 [==============================] - 129s 71ms/step
2022-08-10 17:05:45.346386: W tensorflow/core/common_runtime/bfc_allocator.cc:457] Allocator (GPU_0_bfc) ran out of memory trying to allocate 886.00MiB (rounded to 929038336)requested by op ConcatV2
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation.
Current allocation summary follows.
Current allocation summary follows.
2022-08-10 17:05:45.346816: I tensorflow/core/common_runtime/bfc_allocator.cc:1004] BFCAllocator dump for GPU_0_bfc
2022-08-10 17:05:45.350113: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (256):  Total Chunks: 94, Chunks in use: 94. 23.5KiB allocated for chunks. 23.5KiB in use in bin. 9.1KiB client-requested in use in bin.

...

2022-08-10 17:05:45.987255: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at concat_op.cc:158 : Resource exhausted: OOM when allocating tensor with shape[56704,2048,2] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
ERROR:root:Error processing file E:/Ava/Experiment_2/Exp2_DAS_selections/test_set/outtest_set\rec2021-08-23_17-37-00_02_04.wav.
Traceback (most recent call last):
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\das\predict.py", line 446, in cli_predict
    events, segments, class_probabilities, class_names = predict(x, None, verbose, batch_size,
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\das\predict.py", line 343, in predict
    class_probabilities = predict_probabililties(x, model, params, verbose, prepend_data_padding)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\das\predict.py", line 28, in predict_probabililties
    y_pred = model.predict(pred_gen, verbose=verbose)  # run the network
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1766, in predict
    all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\util\nest.py", line 1376, in map_structure_up_to
    return map_structure_with_tuple_paths_up_to(
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\util\nest.py", line 1474, in map_structure_with_tuple_paths_up_to
    results = [
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\util\nest.py", line 1475, in <listcomp>
    func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\util\nest.py", line 1378, in <lambda>
    lambda _, *values: func(*values),  # Discards the path arg.
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2853, in concat
    return array_ops.concat(tensors, axis=axis)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1769, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1212, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\Ava Kiai\.conda\envs\das\lib\site-packages\tensorflow\python\framework\ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[56704,2048,2] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ConcatV2] name: concat
```

I'm wondering: 
1. Are these two error messages referencing the same problem?
2. Might there be a way I can optimize my graphics card or memory allocation to make this run on my local machine?
3. Could it be that DAS believes the whole 450 s file is one segment (as per some of the indications above) and that's why it's crashing, but would work fine if some parameters were better tuned?

I've sent you the model I'm using, train/predict scripts, and some data for testing via email. I hope this might help parse this. 

Thanks again!

DAS version info:
```
INFO:das.cli:  Windows-10-10.0.22000-SP0
INFO:das.cli:  DAS v0.26.6
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.33.0
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.6.0
INFO:das.cli:  keras v2.6.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
INFO:das.cli:  pandas v1.4.3
INFO:das.cli:  numpy v1.23.1
INFO:das.cli:  h5py v3.7.0
INFO:das.cli:  scipy v1.8.1
INFO:das.cli:  scikit-learn v1.1.1
INFO:das.cli:  xarray v2022.3.0
```

System info: I'm running on Windows 11 64-bit, with an NVIDIA GeForce MX450.

**Comment by postpop** [comment]
Yes, I think they both point to the same problem. The first one may also be an oom error [https://github.com/tensorflow/tensorflow/issues/9489#issuecomment-331639832](). 

To reduce memory usage, you could reduce the batch size. That way less of the data is processed at once by the GPU. It's currently 256 and your GPU has only 1249MB of memory. Try running this with a batch size of 32 or even lower values.

Or you run the inference on the CPU - may take a little longer but at least it runs. You can force tensorflow to use the CPU like so:
```
import tensorflow as tf
# Hide GPU from visible devices
tf.config.set_visible_devices([], 'GPU')

# run the rest here
```

**Comment by postpop** [comment]
Looking at the second error message again, it seems that one fails after all batches have been processed. This frequently happens with long recordings, since at some point tensorflow's `predict` holds the full prediction in memory. 

We have an experimental version of DAS on github that prevents this by processing and saving the predictions batch-by-batch. You could give this a try by updating DAS to the version that is currently on github:
`pip install git+https://github.com/janclemenslab/das --upgrade --no-deps --force`
This works well in our hands but ymmv.

**Comment by postpop** [comment]
Closing this since memory usage is much reduced in the latest version of DAS thanks to the use of dask arrays.
