### ISSUE TITLE
das.train_tune : Error

### ISSUE THREAD

**Issue by emilierp** [janclemenslab/das#52]
Hello, 

I am trying to use the das.train_tune function on Colab.

`
das.train_tune.train(model_name='tcn_stft',
                    data_dir=path_data,
                    save_dir=path_res,
                    save_name=save_name,
                    batch_size = 8, #32
                    verbose=2
                    )
`

But I get the following error : 
`
ERROR:das.train_tune:Something went wrong. Will try to continue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/das/train_tune.py", line 109, in run_trial
    verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/das/data.py", line 249, in __getitem__
    replace=False)
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-12-ba0751aa2c8c>](https://localhost:8080/#) in <module>
      4                     save_name=save_name,
      5                     batch_size=8, # 32
----> 6                     verbose=2
      7                     )

6 frames
[/usr/local/lib/python3.7/dist-packages/das/train_tune.py](https://localhost:8080/#) in train(data_dir, x_suffix, y_suffix, save_dir, save_prefix, save_name, model_name, nb_filters, kernel_size, nb_conv, use_separable, nb_hist, ignore_boundaries, batch_norm, nb_pre_conv, pre_nb_dft, pre_kernel_size, pre_nb_filters, pre_nb_conv, upsample, dilations, nb_lstm_units, verbose, batch_size, nb_epoch, learning_rate, reduce_lr, reduce_lr_patience, fraction_data, seed, batch_level_subsampling, augmentations, tensorboard, wandb_api_token, wandb_project, wandb_entity, log_messages, nb_stacks, with_y_hist, balance, version_data, tune_config, nb_tune_trials, _qt_progress)
    445         verbose=verbose,
    446         callbacks=callbacks,
--> 447         class_weight=params['class_weights'],
    448     )
    449     logger.info(tuner.results_summary())

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/base_tuner.py](https://localhost:8080/#) in search(self, *fit_args, **fit_kwargs)
    207                     step=tuner_utils.get_best_step(results, self.oracle.objective),
    208                 )
--> 209             self.on_trial_end(trial)
    210         self.on_search_end()
    211 

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/base_tuner.py](https://localhost:8080/#) in on_trial_end(self, trial)
    262             self.logger.report_trial_state(trial.trial_id, trial.get_state())
    263 
--> 264         self.oracle.end_trial(trial.trial_id, trial_module.TrialStatus.COMPLETED)
    265         self.oracle.update_space(trial.hyperparameters)
    266         # Display needs the updated trial scored by the Oracle.

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/oracle.py](https://localhost:8080/#) in end_trial(self, trial_id, status)
    259         trial.status = status
    260         if status == trial_lib.TrialStatus.COMPLETED:
--> 261             self.score_trial(trial)
    262         self.end_order.append(trial_id)
    263         self._save_trial(trial)

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/oracle.py](https://localhost:8080/#) in score_trial(self, trial)
    162             trial: A completed `Trial` object.
    163         """
--> 164         trial.score = trial.metrics.get_best_value(self.objective.name)
    165         trial.best_step = trial.metrics.get_best_step(self.objective.name)
    166 

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/metrics_tracking.py](https://localhost:8080/#) in get_best_value(self, name)
    229 
    230     def get_best_value(self, name):
--> 231         self._assert_exists(name)
    232         return self.metrics[name].get_best_value()
    233 

[/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/metrics_tracking.py](https://localhost:8080/#) in _assert_exists(self, name)
    284     def _assert_exists(self, name):
    285         if name not in self.metrics:
--> 286             raise ValueError("Unknown metric: %s" % (name,))
    287 
    288 

ValueError: Unknown metric: val_loss
`

Any help is much appreciated!

**Comment by postpop** [comment]
Hi,

Not sure what the issues is. Looks like the validation data is too short or empty. Tuning requires validation data to be in the data set. If that's not it, can you try to run this locally with the latest version of DAS? Colab uses an older python version (3.7) and the libraries tuning relies on my not supported that python 3.7.
