### ISSUE TITLE
DAS gui spectrogram y-axis floating/not aligned to spectrogram itself

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#77]
Hi there, 

I've had an issue (with multiple versions of DAS) whereby the y-axis on the spectrogram is sort of floating and not aligned with the boundaries of the spectrogram itself (Fig. 1). This is the case regardless of changes to spectrogram settings (bandpass filter, newer spectrogram view settings, or use of audio sample rate or 1k sample rate). 

Up to now I've always just tried to visually infer where the frequency markings should be, but this is now becoming an issue (and I find I have to open the file in another software like Avisoft in order to see the frequency markings accurately). 

Is there some setting I've messed up? If not, hopefully it's a relatively simple fix? 

Thanks!

Fig. 1
![image](https://github.com/user-attachments/assets/3449e569-5ec1-44d0-9cbd-53c929271e4b)

NB: Windows 11 and das version 0.32.3 I believe.

**Comment by postpop** [comment]
Hi, I checked this on win 11 with a newly installed DAS and I cannot reproduce this issue.
Is this happening in a fresh install or after installing additional packages (seaborn et al.)?

**Comment by postpop** [comment]
very strange. can you print the output of `das version` just to be safe?

I see that pyqtgraph is version 0.12.4 on your machine, should be 0.13.7.
Can you try to install the new version? This should do it: `"mamba install pyqtgraph==0.13.7"`

**Comment by avakiai** [comment]
Output of `das version`:

```
INFO:das.cli:  Windows-10-10.0.22631-SP0
INFO:das.cli:  DAS v0.32.3
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.35.7
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.10.0
INFO:das.cli:  keras v2.10.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.9.18 (main, Sep 11 2023, 13:30:38) [MSC v.1916 64 bit (AMD64)]
INFO:das.cli:  pandas v2.2.3
INFO:das.cli:  numpy v1.23.5
INFO:das.cli:  h5py v3.11.0
INFO:das.cli:  scipy v1.13.1
INFO:das.cli:  scikit-learn v1.5.2
INFO:das.cli:  xarray v2024.7.0

```

**Comment by avakiai** [comment]
Is there a way to download this from conda-forge or pip? Our institute (MPI affiliated) firewall now blocks access to repo.anaconda.com (and I am assuming therefore also mamba commands) in order not to commit accidental terms of service breaches after [Anaconda T&C change](https://www.theregister.com/2024/08/08/anaconda_puts_the_squeeze_on/). 

When I try to run the command you suggested, I get a long error report that looks like so: 
```
Looking for: ['pyqtgraph==0.13.7']

pkgs/main/win-64         [====================] (00m:27s) 0 Failed
pkgs/main/noarch         [>                   ] (00m:27s) Timeout was reached
pkgs/r/win-64            [>                   ] (00m:27s) Timeout was reached
pkgs/r/noarch            [>                   ] (00m:27s) Timeout was reached
pkgs/msys2/win-64        [>                   ] (00m:27s) Timeout was reached
pkgs/msys2/noarch        [>                   ] (00m:20s) Timeout was reached

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\mamba.py", line 882, in exception_converter
        raise e
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\mamba.py", line 716, in do_call
        exit_code = install(args, parser, "install")
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\mamba.py", line 514, in install
        index = load_channels(pool, channels, repos)
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\utils.py", line 93, in load_channels
        index = get_index(
      File "C:\ProgramData\Anaconda3\lib\site-packages\mamba\utils.py", line 74, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (28) Timeout was reached [https://repo.anaconda.com/pkgs/main/noarch/repodata.json]

`$ C:\ProgramData\Anaconda3\Scripts\mamba install pyqtgraph==0.13.7`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=das_fresh
                CONDA_EXE=C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\Anaconda3\envs\das_fresh
           CONDA_PREFIX_1=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(das_fresh)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Ava Kiai
                     PATH=# long output...
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : das_fresh
    active env location : C:\ProgramData\Anaconda3\envs\das_fresh
            shell level : 2
       user config file : C:\Users\Ava Kiai\.condarc
 populated config files : C:\Users\Ava Kiai\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __cuda=12.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda3  (read only)
      conda av data dir : C:\ProgramData\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Ava Kiai\.conda\pkgs
                          C:\Users\Ava Kiai\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Ava Kiai\.conda\envs
                          C:\Users\Ava Kiai\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.22631
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

```

**Comment by avakiai** [comment]
... Realizing that mamba or plain conda install would not work because of aforementioned firewall issue, I tried with pip and broke a bunch of things...: 

```
(das_fresh) C:\Users\Ava Kiai>pip install "pyqtgraph==0.13.7" --force-reinstall
Defaulting to user installation because normal site-packages is not writeable
Collecting pyqtgraph==0.13.7
  Using cached pyqtgraph-0.13.7-py3-none-any.whl.metadata (1.3 kB)
Collecting numpy>=1.22.0 (from pyqtgraph==0.13.7)
  Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl.metadata (59 kB)
Using cached pyqtgraph-0.13.7-py3-none-any.whl (1.9 MB)
Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
   ---------------------------------------- 15.9/15.9 MB 15.4 MB/s eta 0:00:00
Installing collected packages: numpy, pyqtgraph
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\Ava Kiai\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deeplabcut 2.3.5 requires statsmodels>=0.11, which is not installed.
hdbscan 0.8.29 requires cython>=0.27, which is not installed.
napari 0.4.18 requires appdirs>=1.4.4, which is not installed.
napari 0.4.18 requires jsonschema>=3.2.0, which is not installed.
napari 0.4.18 requires numpydoc>=0.9.2, which is not installed.
napari 0.4.18 requires sphinx<5,>=4.3.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
tensorpack 0.11 requires pyzmq>=16, which is not installed.
tensorpack 0.11 requires tabulate>=0.7.7, which is not installed.
das 0.32.3 requires matplotlib_scalebar, which is not installed.
xarray-behave 0.35.7 requires pysoundfile, which is not installed.
Successfully installed numpy-2.0.2 pyqtgraph-0.13.7

(das_fresh) C:\Users\Ava Kiai>das gui
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\das_fresh\Scripts\das-script.py", line 6, in <module>
    from das.cli import main
  File "C:\ProgramData\Anaconda3\envs\das_fresh\lib\site-packages\das\cli.py", line 4, in <module>
    from . import train, predict, evaluate
  File "C:\ProgramData\Anaconda3\envs\das_fresh\lib\site-packages\das\train.py", line 4, in <module>
    import flammkuchen as fl
  File "C:\ProgramData\Anaconda3\envs\das_fresh\lib\site-packages\flammkuchen\__init__.py", line 4, in <module>
    import tables
  File "C:\Users\Ava Kiai\AppData\Roaming\Python\Python39\site-packages\tables\__init__.py", line 62, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables\utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

**Comment by postpop** [comment]
Yeah, pip will mess everything up. A bit annoying that MPI now blocks access to all anaconda repos...
Can you try installing DAS with the version of pyqtgraph specified explictly?
`mamba create python=3.9 das=0.32.3 "numpy<1.24" pyqtgraph=0.13.7 -c conda-forge -c ncb -c anaconda -c nvidia -n das -y`

**Comment by avakiai** [comment]
Is this pointing to the same firewall problem? 

```
(das_fresh) C:\Users\Ava Kiai>mamba create python=3.9 das=0.32.3 "numpy<1.24" pyqtgraph=0.13.7 -c conda-forge -c ncb -c anaconda -c nvidia -n das_fresh2 -y

...

Looking for: ['python=3.9', 'das=0.32.3', "numpy[version='<1.24']", 'pyqtgraph=0.13.7']

ncb/win-64               [====================] (00m:00s) No change
ncb/noarch               [====================] (00m:00s) No change
nvidia/noarch            [====================] (00m:00s) No change
nvidia/win-64            [====================] (00m:00s) No change
anaconda/noarch          [====================] (00m:00s) Done
anaconda/win-64          [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:06s) Done
conda-forge/win-64       [====================] (00m:10s) Done
Encountered problems while solving.
Problem: package pyside2-5.15.8-py39hdfd5cee_3 requires qt-main >=5.15.8,<5.16.0a0, but none of the providers can be ind

```

**Comment by postpop** [comment]
Let me try to build the package without the anaconda channel. May take a couple of days since version conflicts will need to be resolved. Will keep you posted!

**Comment by avakiai** [comment]
Thanks a lot Jan!

Are you guys also experiencing the anaconda boycott? I'm curious how other
people are working around this...

Ava Kiai
PhD Candidate, Brain and Behavior Heisenberg Group
<https://www.julio-hechavarria.com/>
<https://www.julio-hechavarria.com/>

Ernst Strüngmann Institute (ESI) gGmbH for Neuroscience

in Cooperation with Max Planck Society

Deutschordenstraße 46

60528 Frankfurt am Main

Germany


***@***.***

***@***.***
avakiai.com

**Comment by postpop** [comment]
Our IT juts sent an email to day announcing plans to block anaconda.
It's fine for most packages, except tensorflow... Hopefully, I get this to built w/o anaconda.

**Comment by avakiai** [comment]
Dear Jan, 

I just tested the new install of das 0.32.4 and the problem is fixed! 

![image](https://github.com/user-attachments/assets/68d4a8ef-617f-4943-a9fd-5b8906a24e6c)

Thank you so much!
